package com.example.BloggingServers.entity;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.util.Date;
import java.util.List;

/**
 * Represents a blog post entity.
 */
@Entity
@Getter
@Setter
@FieldDefaults(level = AccessLevel.PRIVATE)
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Post {

    /**
     * Unique identifier for the post.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    /**
     * The title of the post.
     */
    String name;

    /**
     * The content/body of the post.
     */
    @Column(length = 5000) // Maximum length of 5000 characters.
    String content;

    /**
     * The author/creator of the post.
     */
    String postedBy;

    /**
     * The URL of an image associated with the post.
     */
    String img;

    /**
     * The date when the post was created.
     */
    Date date;

    /**
     * The number of likes the post has received.
     */
    int likedCount;

    /**
     * The number of views the post has received.
     */
    int viewCount;

    /**
     * The list of tags associated with the post.
     */
    List<String> tags;

    // Getters, setters, builder, and constructors are generated by Lombok annotations.
}
